/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/game` | `/game`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/venues` | `/venues`; params?: Router.UnknownInputParams; } | { pathname: `/feed/add-post`; params?: Router.UnknownInputParams; } | { pathname: `/[...messing]`, params: Router.UnknownInputParams & { messing: (string | number)[]; } } | { pathname: `/feed/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/game` | `/game`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/venues` | `/venues`; params?: Router.UnknownOutputParams; } | { pathname: `/feed/add-post`; params?: Router.UnknownOutputParams; } | { pathname: `/[...messing]`, params: Router.UnknownOutputParams & { messing: string[]; } } | { pathname: `/feed/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/login${`?${string}` | `#${string}` | ''}` | `/onboarding${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/game${`?${string}` | `#${string}` | ''}` | `/game${`?${string}` | `#${string}` | ''}` | `${'/(app)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/venues${`?${string}` | `#${string}` | ''}` | `/venues${`?${string}` | `#${string}` | ''}` | `/feed/add-post${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/game` | `/game`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/venues` | `/venues`; params?: Router.UnknownInputParams; } | { pathname: `/feed/add-post`; params?: Router.UnknownInputParams; } | `/${string}` | `/feed/${Router.SingleRoutePart<T>}` | { pathname: `/[...messing]`, params: Router.UnknownInputParams & { messing: (string | number)[]; } } | { pathname: `/feed/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
